### ISSUE TITLE
Transfers source

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#190] opened 2018-11-16 10:28 UTC
This is a query: parsing Transfers

Name: Cash unit
Source: Kin
Transfer type: Cash
Marked invalid

Does 'source: Kin' need to be added anywhere under  'resource type'? If so, where? Or do I simply parse as 'valid'?

**Comment by daiClegg** [comment] 2018-11-25 17:38
What's the status of this pls?
There's no tags on it so i don't know if it's a bug or maybe unclear UI or unclear doc?
Or in need of an RST change.

If it needs testing/fixing, can we have steps to reproduce please?

**Comment by celiapetty** [comment] 2018-11-26 12:42
Source 'kin' was parsed as valid. For discussion-source probably needs to be included in Resource sub type eg 'Cash, kin' ; 'Maize, food aid'. These points need to be agreed before we produce the next version of the User Guide. Tagged for discussion (domain experts) as I don't think there are engineering implications

**Comment by daiClegg** [comment] 2018-11-26 21:44
Right now a Transfer is either tagged as either official or unofficial after discussion with John (and Celia?)

John's summary in that thread was:

> Transfers; after several tries I settled on 'Official transfers' & 'Other transfers' - the assumption being that the specific origin of the transfer eg oxfam, brother, and the type of transfer eg maize will be supplied by the entry. 'Gift of maize from brother'/other.  As far as I can see there are just too many potential types and sources  of transfer to make a useable classification : some transfers are mixed food and cash, animals, clothes, school meals etc
My conclusion at the time of the dialogue (May '18):

My conclusion (after more exchanges:

> So my example of “Gift of Maize from brother”, taken from an actual interview, would have to be manually categories as a Maize transfer and an unofficial transfer, from kin/family.
> If we separate that our to Type - ‘Unofficial'; Source - ‘Kin/Family’; Content - ‘Maize' then we can do a lot more automatically with no real cost in data entry. And of course extracting individual items, as you do, is still possible.


So the key distinction (official/unofficial) is captured and is definitive. The Source is not validated because John felt there  is not a definitive list of sources that is worth categorising by.

We might consider adding a drop-down of likely sources (e.g. Kin) but allow others, if that would be valuable.

**Comment by daiClegg** [comment] 2018-11-27 23:09
John's Comment:
> Your proposal in the thread seems to work -(Type - ‘Unofficial'; Source - ‘Kin/Family’; Content - ‘Maize').
> 
> Kin/ family could be reduced to kin or family or relative.  
> 
> However it could (rarely) be from an unrelated person e.g. a neighbour, landlord whatever so Kin(or familiy, or relative)/ neighbour/(or aquaintance? unrelated person?). Unrelated person is probably clearest. Relative/unrelated person covers it - it avoids the problem of an unenterable item.

**Comment by daiClegg** [comment] 2018-11-27 23:16
Celia, John:CAn you review the Transfer types  pleasse.

Transfers are categorised as Cash, Food or Other and there is a short list of TYpes (Cash,Food, Fertilizer, Pension) for testing. We shoul dtry to have a definitive list before the first produciton use in February.

But from a 'bug' point of view, i will close this now,

**Closed by daiClegg** 2018-11-27 23:16 UTC
Labels: For Discussion (domain experts)
