### ISSUE TITLE
Add new household member, OIHM, Year of Birth

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#614] opened 2021-03-04 16:02 UTC
Instance QA
OIHM
Study: New cattle 2020
Module: Household
Entering a new household directly into the software. Name and number added
Click on household member, new
Household member name-ok
Household member number-grey, can't enter a number
Age-OK
Year of birth-grey, can't enter a number
Can't save and continue: error message: Value for year of birth in household member  is required
Name and number

**Comment by daiClegg** [comment] 2021-03-04 17:13
Can't enter HHM number - correct; it is autogenerated to stop a user from entering duplicates.
Can't enter year - correct; it is calculated from the age, but is then used in analysis to take account of time elapsing between survey and reporting.

I just tried this and it works as i had expected.
I nearly just closed it 'does not reproduce', leaving you to prove there was a problem.
But instead, i tried different combinations of key strokes and sequences that you might have used until i worked out that you didn't save the household record before entering the household member. 

If you had told me what you *did*, (ie the steps to reproduce, every single keystroke) rather than just the result, i would have known instantly what the problem was and saved that time.

**Closed by daiClegg** 2021-03-04 17:13 UTC
Labels: Clarification, Not a bug

**Comment by celiapetty** [comment] 2021-03-05 10:52
Got it-I will include in the new video narrative I'm currently writing,  a reminder to save the Household _before_ adding household members

**Comment by daiClegg** [comment] 2021-03-05 18:09
As a general rule in OIHM & OHEA, where you have a module that allows you to create a new item, then add sub-items that belong to it, as in this case, it's probably safer to save the main item before adding others anyway.

**Comment by celiapetty** [comment] 2021-03-08 17:53
Noted: will stress this point  in the next training video
