### ISSUE TITLE
Multiple unnecessary validation complete notifications

### ISSUE THREAD

**Issue by stellangoleka** [dbrownukk/EFD_v2#346] opened 2019-07-16 14:54 UTC
Is it necessary to have multiple messages of 'Validation Complete'. Will be possible to have only one message?
![image](https://user-images.githubusercontent.com/45176194/61304965-4860cc80-a7ea-11e9-8321-b080407df17b.png)

**Comment by stellangoleka** [comment] 2019-07-16 14:57
Similarly, only one item was invalid but the message came in multiple ways.
![image](https://user-images.githubusercontent.com/45176194/61305157-9d044780-a7ea-11e9-95c1-9509484e3840.png)

**Comment by daiClegg** [comment] 2019-07-16 17:02
@stellangoleka Please assign your new issues to yourself and me if they are to do with the software or to you, me, Celia & John if they are to do with methodology.
Just me and you if you're unsure

**Comment by daiClegg** [comment] 2019-07-16 17:03
this is a duplicate of #343

**Closed by daiClegg** 2019-07-16 17:03 UTC
Labels: bug, duplicate
