### ISSUE TITLE
Parse the uploaded spreadsheet data into intermediate resource tables

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#63] opened 2018-02-24 15:08 UTC

**Comment by dbrownukk** [comment] 2018-03-14 18:00
Dai,

Set this issue to Testing but need to walk you through - many questions on spreadsheet and data.

But spreadsheet is loading and data is visible... at least managed to load the 20_WG_NGombere July 2016 - Stephen populated spreadsheet into Mukono Middle. BUT, suspect we will need many spreadsheets and a good degree of debugging and rewrite to harden the code.

Some of these we know about - just a reminder of things to tackle.

1. Tradeable asset - where is tradeable data in spreadsheet?
2. Need Market and Work Location data
3. On Parse the WealthGroupInterview is set to Parsed. It cannot be reparsed without setting back to Uploaded. Left as updateable status for the moment.
4. Asset Resource Type is used - need to move to Asset Resource Sub Type as the reference..
5. Strings, Numbers and Dates in the spreadsheet - need to create a generic fetch rather than assuming type is correct - if type is wrong then fetch fails - i.e. Other had a Number 10 in it which was determined to be a Number and failed with a String fetch being used
6. AssetFoodStock - is this 'FOOD PURCHASE' on spreadsheet. No model of Unit, Quantity or PPU if it is.
7. Where should 'NON FOOD PURCHASE' on spreadsheet go?

Anyway - not so bad but will undoubtedly fail as we try more data. Glass half empty at the moment

**Comment by daiClegg** [comment] 2018-03-15 22:22
See Project = "Mukono - Trial"
       Community = "Namakwa. Nakisunga"   (Interview = 3)
       Wealth Group = "Poor"

I uploaded a spreadsheet to this WG I/V successfully, saved it and manually set the status to "Uploaded"
I the pressed the "Parse Spreadsheet" button and got 2 error messages:

>Incomplete Spreadsheet data, correct spreadsheet and upload again
>Impossible to execute Parse spreadsheet action: java.lang.IllegalStateException: Cannot get a text value from a numeric cell

I can't tell from this where the error is in the spreadsheet (which is the actual real data from this actual real project)

I need to find what is actually wrong with this spreadsheet, so we can tell if it's a data error or a parser error,  and to do that it would help if there was a better error message, cos there's always the chance of data errors even when the parser is debugged.

The data is stil there and reproduces

**Comment by daiClegg** [comment] 2018-03-15 22:23
If you need me to pick through the spreadsheet to find the data error, re-assign to me.

**Comment by dbrownukk** [comment] 2018-03-17 13:02
Needs improved Java exception catch - will subdivide by asset type.

**Comment by daiClegg** [comment] 2018-03-17 13:18
David,

I have all 22 spreadsheets from the Mukono study. That’s why i’ve set up a project with all 22 WGs.
I haven’t populated the characteristic resources for the WGs, cos we’ve tested that and it doesn't add to testing the loader scenarios.

When i’ve caught up with the backlog 'For Testing', i will work my way through all the 22.
That still won’t make me 100% confident, but it will give me confidence to widen the test base.

When would be good to walk me through how i should test? Probably not before Monday for me.

EfD board meeting is on 21st, so i can go to that now the UKOUG SIG meeting is off, and demo them M1. Maybe even an M2 instance - if i’ve got at least one spreadsheet that will load - should be able to repeat your test case at the very least. I’d like to have you come and demo and present to the board at some point, maybe next one?

Board will also be discussing OIHM. Any chance of a short proposal before then? No prob if not, but might help make progress if there is.
Key question the board will have is about the risks - what happens if we don't get as far as we’d like for £10k. They might have to rummage down the back of the sofa for the next pot, so they’ll want to feel more comfortable about how big that pot might be and how likely it is they’ll need to provide it, Given that, i think we don't want to try to rush them to a decision next week, just move them forward - and demoing the OHEA progress will be key for that,

Have a good weekend. 

cheers
dai

**Comment by dbrownukk** [comment] 2018-03-19 09:05
Good Morning,
Anytime today will work after 10 
Just writing an error checker for the spreadsheet to identify the failing spreadsheet cell dueing the parse. The lack of the generic template makes this hard coded but not the end of the world.. We could just examine the stack trace each time, but not really acceptable!
Will get proposal done today..
cheers,
David 


    On Saturday, 17 March 2018, 13:18:21 GMT, dai clegg <notifications@github.com> wrote:  
 
 David,

I have all 22 spreadsheets from the Mukono study. That’s why i’ve set up a project with all 22 WGs.
I haven’t populated the characteristic resources for the WGs, cos we’ve tested that and it doesn't add to testing the loader scenarios.

When i’ve caught up with the backlog 'For Testing', i will work my way through all the 22.
That still won’t make me 100% confident, but it will give me confidence to widen the test base.

When would be good to walk me through how i should test? Probably not before Monday for me.

EfD board meeting is on 21st, so i can go to that now the UKOUG SIG meeting is off, and demo them M1. Maybe even an M2 instance - if i’ve got at least one spreadsheet that will load - should be able to repeat your test case at the very least. I’d like to have you come and demo and present to the board at some point, maybe next one?

Board will also be discussing OIHM. Any chance of a short proposal before then? No prob if not, but might help make progress if there is.
Key question the board will have is about the risks - what happens if we don't get as far as we’d like for £10k. They might have to rummage down the back of the sofa for the next pot, so they’ll want to feel more comfortable about how big that pot might be and how likely it is they’ll need to provide it, Given that, i think we don't want to try to rush them to a decision next week, just move them forward - and demoing the OHEA progress will be key for that,

Have a good weekend. 

cheers
dai

**Comment by dbrownukk** [comment] 2018-03-19 18:50
See Project = "Mukono - Trial"
Community = "Namakwa. Nakisunga"   (Interview = 3)
Wealth Group = "Poor"

Now parses..

Extra validation in place but am sure other anomalies will arise..

**Comment by daiClegg** [comment] 2018-03-19 22:32
Successfully parsed that spreadsheet (having added a Year Description)
Will press onto others next...

**Comment by daiClegg** [comment] 2018-03-21 21:46
Some notes on loading Mukono Trial spreadsheets

Subdistrict/Wealth Group


Bugoya/Better-off          

incomplete Spreadsheet data, correct spreadsheet and upload again
Impossible to execute Parse spreadsheet action:  java.lang.IllegalStateException: Cannot get a text value from a numeric cell

Bugoya/Poor

same as above

Bugoya/Middle

Incomplete Spreadsheet data, correct spreadsheet and upload again
Impossible to execute Parse spreadsheet action: java.lang.NullPointerException

I'm sure they are data errors, but we need make it easier to find and fix.

**Comment by daiClegg** [comment] 2018-03-21 22:00
Some more results:

Lusera/Nakisonga MIddle

Parses

Lusera/Nakisonga Very Poor

Incomplete Spreadsheet data, correct spreadsheet and upload again
Impossible to execute Parse spreadsheet action: java.lang.IllegalStateException: Cannot get a text value from a numeric cell

Lusera/Nakisonga Poor

Parses.

Lusera/Nakisonga Better-off
Incomplete Spreadsheet data, correct spreadsheet and upload again
Impossible to execute Parse spreadsheet action: java.lang.IllegalStateException: Cannot get a numeric value from a text cell


Namakwe/Nakisunga Better-off

Parses.

The problem may be eliminated if these had been created with our generated spreadsheet - presumably that has cell types matching the celll types the parser is expecting.

Data erorrs will still occur, so we do need to be defensive, but this is possibly a repeat of a single data colleciton error that wil be eliminated in future

**Comment by daiClegg** [comment] 2018-03-21 22:01
btw, all these spreadsheets are attached to the respective WG I/V records in the Mukono Trial project.

**Comment by dbrownukk** [comment] 2018-03-22 08:39
Using latest code on my machine - I did not do a release yesterday due to your demo - of the 4 WG Interview spreadsheets for Mukono Trial, 2 load successfully, 1 reports a missing data field correctly and one fails with java exception. 

Having to code around cell types - null, blank, number, text. extra rows, moved rows...  all doable 

The more examples the better..

thanks

**Comment by daiClegg** [comment] 2018-03-22 21:26
Remaining MukonoTYrial loads as follows (no notes if Parse ok):

Mengo/Mpunge Poor

Incomplete Spreadsheet data, correct spreadsheet and upload again
Impossible to execute Parse spreadsheet action: java.lang.IllegalStateException: Cannot get a numeric value from a text cell

Mugomba/Mpata Better off

Incomplete Spreadsheet data, correct spreadsheet and upload again
Impossible to execute Parse spreadsheet action: java.lang.IllegalStateException: Cannot get a numeric value from a text cell

Mubera/Mpatta Better-off

Incomplete Spreadsheet data, correct spreadsheet and upload again
Impossible to execute Parse spreadsheet action: java.lang.IllegalStateException: Cannot get a numeric value from a text cell

Mugomba/Mpata Better-off

Incomplete Spreadsheet data, correct spreadsheet and upload again
Impossible to execute Parse spreadsheet action: java.lang.IllegalStateException: Cannot get a numeric value from a text cell

**Comment by daiClegg** [comment] 2018-03-22 21:44
and some more:

Ngombere/Mpunge Middle

Incomplete Spreadsheet data, correct spreadsheet and upload again
Impossible to execute Parse spreadsheet action: java.lang.IllegalStateException: Cannot get a text value from a numeric cell

**Comment by daiClegg** [comment] 2018-03-22 21:47
Butere/Mpatta Middle

Incomplete Spreadsheet data, correct spreadsheet and upload again
Impossible to execute Parse spreadsheet action: java.lang.IllegalStateException: Cannot get a text value from a numeric cell

**Comment by daiClegg** [comment] 2018-03-22 21:56
Mugombe/Mpatta Poor

Incomplete Spreadsheet data, correct spreadsheet and upload again
Impossible to execute Parse spreadsheet action: java.lang.IllegalStateException: Cannot get a text value from a numeric cell

Mugomba/Mpatta Better-off

Incomplete Spreadsheet data, correct spreadsheet and upload again
Impossible to execute Parse spreadsheet action: java.lang.IllegalStateException: Cannot get a text value from a numeric cell

Mugomba/Mpatta Middle

Incomplete Spreadsheet data, correct spreadsheet and upload again
Impossible to execute Parse spreadsheet action: java.lang.IllegalStateException: Cannot get a numeric value from a text cell



Not every spreadsheet loaded matches the  WG interview record because some of the spreadsheets have ambiguous or unfathomable names.
So i made sure i loaded a different spreadsheet for each WG I/V record in the database to maximise test coverage.

I have not loaded spreadsheets 18 or 23. But i guess this is enough for tonight...

**Comment by dbrownukk** [comment] 2018-03-23 18:20
Think I have cracked most of the issues, no doubt others will arrive. Crazy that some cells cannot be read and you have to trap a java exception rather reading a value. Trapping a unique exception for every cell seems excessive.

**Comment by daiClegg** [comment] 2018-03-24 12:51
I have also parsed the only 2 other real-world examples i have to hand. 

One parsed.
The other failed with an appropriate error; it told me the column that was missing and when i corrected that, it parsed.

As you say further edge cases may well emerge and I will seek out more test data to try to find them, but closing this issue as a completed new feature.

**Closed by daiClegg** 2018-03-24 12:51 UTC
Labels: Feature Story
