### ISSUE TITLE
Generate community interview template from OHEA software

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#625] opened 2021-04-15 13:15 UTC
I may have missed this, but I don't think that currently it's possible to generate a blank Community interview template in OHEA? In HEA studies to date, community interview data has been recorded on a separate spreadsheet (attached). It would be useful if a blank community interview spreadsheet template could be generated
[ExampleBlankCommunityInterview.xlsx](https://github.com/dbrownukk/EFD_v2/files/6318202/ExampleBlankCommunityInterview.xlsx)
 so all documents needed to complete a study are in one place.  Uploading of data from the spreadsheet isn't necessary, although project leaders should be required to save a copy of the completed spreadsheet with other related  project documents
@daiClegg could you estimate the cost please?

**Comment by daiClegg** [comment] 2021-04-21 21:29
This appears to be a WG interview template is it not?

**Comment by celiapetty** [comment] 2021-04-22 13:30
Looks as if I uploaded the wrong file-possibly wrongly labelled . I searched this out from earlier request from John for sample community interview spreadsheet. There should be a template with information needed to complete the community interview-Will extend the search.

**Comment by celiapetty** [comment] 2021-04-27 16:05
Correct template attached (blank )
[Template  community interview  blank.xlsx](https://github.com/dbrownukk/EFD_v2/files/6385998/Template.community.interview.blank.xlsx)

**Comment by celiapetty** [comment] 2021-05-14 10:22
I think we've covered this now?

**Comment by daiClegg** [comment] 2021-05-14 17:27
I will mark this as a duplicate of #637; in fact it is a subset.

**Closed by daiClegg** 2021-05-14 17:27 UTC
Labels: User Action/Decision Required, enhancement
